name: FrizzlenChants
version: '1.0-SNAPSHOT'
main: org.frizzlenpop.frizzlenChants.FrizzlenChants
api-version: '1.21'
load: STARTUP
authors: [ frizzlenpop ]
description: A Plugin for Custom Enchants. 
